/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.15.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QPushButton *CubaUSSR;
    QPushButton *NicaraguaUSA;
    QPushButton *NicaraguaUSSR;
    QPushButton *HaitiUSA;
    QPushButton *HaitiUSSR;
    QPushButton *DominicanRepUSA;
    QPushButton *MoroccoUSA;
    QPushButton *IvoryCoastUSA;
    QPushButton *NigeriaUSA;
    QPushButton *NigeriaUSSR;
    QPushButton *IvoryCoastUSSR;
    QPushButton *MexicoUSA;
    QPushButton *CubaUSA;
    QPushButton *MexicoUSSR;
    QPushButton *GuatemalaUSA;
    QPushButton *GuatemalaUSSR;
    QPushButton *HondurasUSA;
    QPushButton *ElSalvadorUSSR;
    QPushButton *HondurasUSSR;
    QPushButton *ElSalvadorUSA;
    QPushButton *LibyaUSSR;
    QPushButton *LebanonUSSR;
    QPushButton *CanadaUSA;
    QPushButton *EGermanyUSSR;
    QPushButton *EGermanyUSA;
    QPushButton *CanadaUSSR;
    QPushButton *FinlandUSA;
    QPushButton *HungaryUSA;
    QPushButton *HungaryUSSR;
    QPushButton *LebanonUSA;
    QPushButton *AustriaUSA;
    QPushButton *SaharanStatesUSSR;
    QPushButton *WestAfricanStatesUSSR;
    QPushButton *WestAfricanStatesUSA;
    QPushButton *AlgeriaUSA;
    QPushButton *MoroccoUSSR;
    QPushButton *DominicanRepUSSR;
    QPushButton *RomaniaUSA;
    QPushButton *AlgeriaUSSR;
    QPushButton *SaharanStatesUSA;
    QPushButton *SpainPortugalUSSR;
    QPushButton *SpainPortugalUSA;
    QPushButton *AustriaUSSR;
    QPushButton *WGermanyUSSR;
    QPushButton *BeneluxUSSR;
    QPushButton *WGermanyUSA;
    QPushButton *SwedenUSSR;
    QPushButton *SwedenUSA;
    QPushButton *DenmarkUSSR;
    QPushButton *DenmarkUSA;
    QPushButton *NorwayUSSR;
    QPushButton *FinlandUSSR;
    QPushButton *UKUSSR;
    QPushButton *NorwayUSA;
    QPushButton *IsraelUSA;
    QPushButton *IsraelUSSR;
    QPushButton *UKUSA;
    QPushButton *BulgariaUSSR;
    QPushButton *BulgariaUSA;
    QPushButton *EgyptUSA;
    QPushButton *TurkeyUSA;
    QPushButton *EgyptUSSR;
    QPushButton *IraqUSSR;
    QPushButton *LibyaUSA;
    QPushButton *TurkeyUSSR;
    QPushButton *SyriaUSSR;
    QPushButton *IraqUSA;
    QPushButton *SyriaUSA;
    QPushButton *BeneluxUSA;
    QPushButton *FranceUSSR;
    QPushButton *FranceUSA;
    QPushButton *YugoslaviaUSSR;
    QPushButton *ItalyUSSR;
    QPushButton *ItalyUSA;
    QPushButton *YugoslaviaUSA;
    QPushButton *TunisiaUSA;
    QPushButton *TunisiaUSSR;
    QPushButton *GreeceUSSR;
    QPushButton *CzechoslovakiaUSSR;
    QPushButton *RomaniaUSSR;
    QPushButton *PolandUSSR;
    QPushButton *PolandUSA;
    QPushButton *GreeceUSA;
    QPushButton *CzechoslovakiaUSA;
    QGraphicsView *graphicsView;
    QPushButton *CostaRicaUSA;
    QPushButton *CostaRicaUSSR;
    QPushButton *UruguayUSSR;
    QPushButton *UruguayUSA;
    QPushButton *ArgentinaUSA;
    QPushButton *ArgentinaUSSR;
    QPushButton *ChileUSA;
    QPushButton *ChileUSSR;
    QPushButton *ParaguayUSA;
    QPushButton *ParaguayUSSR;
    QPushButton *BrazilUSA;
    QPushButton *BrazilUSSR;
    QPushButton *BoliviaUSA;
    QPushButton *BoliviaUSSR;
    QPushButton *PeruUSA;
    QPushButton *PeruUSSR;
    QPushButton *EcuadorUSA;
    QPushButton *SouthAfricaUSA;
    QPushButton *SouthAfricaUSSR;
    QPushButton *BotswanaUSA;
    QPushButton *BotswanaUSSR;
    QPushButton *ZimbabweUSA;
    QPushButton *ZimbabweUSSR;
    QPushButton *SEAfricanStatesUSA;
    QPushButton *SEAfricanStatesUSSR;
    QPushButton *ZaireUSA;
    QPushButton *ZaireUSSR;
    QPushButton *AngolaUSA;
    QPushButton *AngolaUSSR;
    QPushButton *KenyaUSA;
    QPushButton *KenyaUSSR;
    QPushButton *CameroonUSA;
    QPushButton *CameroonUSSR;
    QPushButton *SomaliaUSA;
    QPushButton *SomaliaUSSR;
    QPushButton *SudanUSA;
    QPushButton *SudanUSSR;
    QPushButton *SaudiArabiaUSA;
    QPushButton *JordanUSA;
    QPushButton *SaudiArabiaUSSR;
    QPushButton *EthiopiaUSSR;
    QPushButton *EthiopiaUSA;
    QPushButton *AustraliaUSA;
    QPushButton *AustraliaUSSR;
    QPushButton *IndonesiaUSA;
    QPushButton *IndonesiaUSSR;
    QPushButton *MalaysiaUSA;
    QPushButton *MalaysiaUSSR;
    QPushButton *BurmaUSA;
    QPushButton *VietnamUSA;
    QPushButton *BurmaUSSR;
    QPushButton *VietnamUSSR;
    QPushButton *ThailandUSA;
    QPushButton *ThailandUSSR;
    QPushButton *PhilippinesUSA;
    QPushButton *PhilippinesUSSR;
    QPushButton *TaiwanChinaUSA;
    QPushButton *TaiwanChinaUSSR;
    QPushButton *LaosCambodiaUSA;
    QPushButton *LaosCambodiaUSSR;
    QPushButton *JapanUSA;
    QPushButton *JapanUSSR;
    QPushButton *ChinaUSA;
    QPushButton *ChinaUSSR;
    QPushButton *SKoreaUSA;
    QPushButton *SKoreaUSSR;
    QPushButton *IndiaUSSR;
    QPushButton *PakistanUSSR;
    QPushButton *JordanUSSR;
    QPushButton *PakistanUSA;
    QPushButton *GulfStatesUSA;
    QPushButton *IndiaUSA;
    QPushButton *IranUSA;
    QPushButton *AfghanistanUSA;
    QPushButton *IranUSSR;
    QPushButton *GulfStatesUSSR;
    QPushButton *AfghanistanUSSR;
    QPushButton *NKoreaUSSR;
    QPushButton *NKoreaUSA;
    QPushButton *EcuadorUSSR;
    QPushButton *PanamaUSA;
    QPushButton *VenezuelaUSSR;
    QPushButton *PanamaUSSR;
    QPushButton *VenezuelaUSA;
    QPushButton *ColombiaUSA;
    QPushButton *ColombiaUSSR;
    QWidget *verticalLayoutWidget;
    QVBoxLayout *Resource_point;
    QTextBrowser *USA_resource;
    QTextBrowser *USSR_resource;
    QPushButton *btn_next;
    QTextBrowser *curr_player_display;
    QTextBrowser *curr_player_head;
    QPushButton *btn_coup;
    QLabel *round1;
    QLabel *round2;
    QLabel *round4;
    QLabel *round3;
    QLabel *round5;
    QLabel *round6;
    QLabel *round7;
    QLabel *turn1;
    QLabel *turn2;
    QLabel *turn3;
    QLabel *turn4;
    QLabel *turn5;
    QLabel *turn6;
    QLabel *turn7;
    QLabel *turn8;
    QLabel *turn9;
    QLabel *turn10;
    QLabel *defcon5;
    QLabel *defcon4;
    QLabel *defcon3;
    QLabel *defcon2;
    QLabel *defcon1;
    QMenuBar *menubar;
    QMenu *menuTwlight_Struggle_Lite;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(2580, 1680);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        centralwidget->setStyleSheet(QString::fromUtf8(""));
        CubaUSSR = new QPushButton(centralwidget);
        CubaUSSR->setObjectName(QString::fromUtf8("CubaUSSR"));
        CubaUSSR->setGeometry(QRect(430, 750, 41, 41));
        NicaraguaUSA = new QPushButton(centralwidget);
        NicaraguaUSA->setObjectName(QString::fromUtf8("NicaraguaUSA"));
        NicaraguaUSA->setGeometry(QRect(370, 850, 41, 41));
        NicaraguaUSSR = new QPushButton(centralwidget);
        NicaraguaUSSR->setObjectName(QString::fromUtf8("NicaraguaUSSR"));
        NicaraguaUSSR->setGeometry(QRect(420, 850, 41, 41));
        HaitiUSA = new QPushButton(centralwidget);
        HaitiUSA->setObjectName(QString::fromUtf8("HaitiUSA"));
        HaitiUSA->setGeometry(QRect(490, 820, 41, 41));
        HaitiUSSR = new QPushButton(centralwidget);
        HaitiUSSR->setObjectName(QString::fromUtf8("HaitiUSSR"));
        HaitiUSSR->setGeometry(QRect(540, 820, 41, 41));
        DominicanRepUSA = new QPushButton(centralwidget);
        DominicanRepUSA->setObjectName(QString::fromUtf8("DominicanRepUSA"));
        DominicanRepUSA->setGeometry(QRect(600, 820, 41, 41));
        MoroccoUSA = new QPushButton(centralwidget);
        MoroccoUSA->setObjectName(QString::fromUtf8("MoroccoUSA"));
        MoroccoUSA->setGeometry(QRect(870, 710, 41, 41));
        IvoryCoastUSA = new QPushButton(centralwidget);
        IvoryCoastUSA->setObjectName(QString::fromUtf8("IvoryCoastUSA"));
        IvoryCoastUSA->setGeometry(QRect(930, 960, 41, 41));
        NigeriaUSA = new QPushButton(centralwidget);
        NigeriaUSA->setObjectName(QString::fromUtf8("NigeriaUSA"));
        NigeriaUSA->setGeometry(QRect(1070, 940, 41, 41));
        NigeriaUSSR = new QPushButton(centralwidget);
        NigeriaUSSR->setObjectName(QString::fromUtf8("NigeriaUSSR"));
        NigeriaUSSR->setGeometry(QRect(1120, 940, 41, 41));
        IvoryCoastUSSR = new QPushButton(centralwidget);
        IvoryCoastUSSR->setObjectName(QString::fromUtf8("IvoryCoastUSSR"));
        IvoryCoastUSSR->setGeometry(QRect(980, 960, 41, 41));
        MexicoUSA = new QPushButton(centralwidget);
        MexicoUSA->setObjectName(QString::fromUtf8("MexicoUSA"));
        MexicoUSA->setGeometry(QRect(90, 690, 41, 41));
        CubaUSA = new QPushButton(centralwidget);
        CubaUSA->setObjectName(QString::fromUtf8("CubaUSA"));
        CubaUSA->setGeometry(QRect(380, 750, 41, 41));
        MexicoUSSR = new QPushButton(centralwidget);
        MexicoUSSR->setObjectName(QString::fromUtf8("MexicoUSSR"));
        MexicoUSSR->setGeometry(QRect(140, 690, 41, 41));
        GuatemalaUSA = new QPushButton(centralwidget);
        GuatemalaUSA->setObjectName(QString::fromUtf8("GuatemalaUSA"));
        GuatemalaUSA->setGeometry(QRect(180, 770, 41, 41));
        GuatemalaUSSR = new QPushButton(centralwidget);
        GuatemalaUSSR->setObjectName(QString::fromUtf8("GuatemalaUSSR"));
        GuatemalaUSSR->setGeometry(QRect(230, 770, 41, 41));
        HondurasUSA = new QPushButton(centralwidget);
        HondurasUSA->setObjectName(QString::fromUtf8("HondurasUSA"));
        HondurasUSA->setGeometry(QRect(260, 850, 41, 41));
        ElSalvadorUSSR = new QPushButton(centralwidget);
        ElSalvadorUSSR->setObjectName(QString::fromUtf8("ElSalvadorUSSR"));
        ElSalvadorUSSR->setGeometry(QRect(200, 860, 41, 41));
        HondurasUSSR = new QPushButton(centralwidget);
        HondurasUSSR->setObjectName(QString::fromUtf8("HondurasUSSR"));
        HondurasUSSR->setGeometry(QRect(310, 850, 41, 41));
        ElSalvadorUSA = new QPushButton(centralwidget);
        ElSalvadorUSA->setObjectName(QString::fromUtf8("ElSalvadorUSA"));
        ElSalvadorUSA->setGeometry(QRect(150, 860, 41, 41));
        LibyaUSSR = new QPushButton(centralwidget);
        LibyaUSSR->setObjectName(QString::fromUtf8("LibyaUSSR"));
        LibyaUSSR->setGeometry(QRect(1210, 750, 41, 41));
        LebanonUSSR = new QPushButton(centralwidget);
        LebanonUSSR->setObjectName(QString::fromUtf8("LebanonUSSR"));
        LebanonUSSR->setGeometry(QRect(1400, 610, 41, 41));
        CanadaUSA = new QPushButton(centralwidget);
        CanadaUSA->setObjectName(QString::fromUtf8("CanadaUSA"));
        CanadaUSA->setGeometry(QRect(420, 380, 41, 41));
        EGermanyUSSR = new QPushButton(centralwidget);
        EGermanyUSSR->setObjectName(QString::fromUtf8("EGermanyUSSR"));
        EGermanyUSSR->setGeometry(QRect(1140, 290, 41, 41));
        EGermanyUSA = new QPushButton(centralwidget);
        EGermanyUSA->setObjectName(QString::fromUtf8("EGermanyUSA"));
        EGermanyUSA->setGeometry(QRect(1090, 290, 41, 41));
        CanadaUSSR = new QPushButton(centralwidget);
        CanadaUSSR->setObjectName(QString::fromUtf8("CanadaUSSR"));
        CanadaUSSR->setGeometry(QRect(470, 380, 41, 41));
        FinlandUSA = new QPushButton(centralwidget);
        FinlandUSA->setObjectName(QString::fromUtf8("FinlandUSA"));
        FinlandUSA->setGeometry(QRect(1280, 140, 41, 41));
        HungaryUSA = new QPushButton(centralwidget);
        HungaryUSA->setObjectName(QString::fromUtf8("HungaryUSA"));
        HungaryUSA->setGeometry(QRect(1210, 450, 41, 41));
        HungaryUSSR = new QPushButton(centralwidget);
        HungaryUSSR->setObjectName(QString::fromUtf8("HungaryUSSR"));
        HungaryUSSR->setGeometry(QRect(1260, 450, 41, 41));
        LebanonUSA = new QPushButton(centralwidget);
        LebanonUSA->setObjectName(QString::fromUtf8("LebanonUSA"));
        LebanonUSA->setGeometry(QRect(1350, 610, 41, 41));
        AustriaUSA = new QPushButton(centralwidget);
        AustriaUSA->setObjectName(QString::fromUtf8("AustriaUSA"));
        AustriaUSA->setGeometry(QRect(1100, 440, 41, 41));
        SaharanStatesUSSR = new QPushButton(centralwidget);
        SaharanStatesUSSR->setObjectName(QString::fromUtf8("SaharanStatesUSSR"));
        SaharanStatesUSSR->setGeometry(QRect(1080, 840, 41, 41));
        WestAfricanStatesUSSR = new QPushButton(centralwidget);
        WestAfricanStatesUSSR->setObjectName(QString::fromUtf8("WestAfricanStatesUSSR"));
        WestAfricanStatesUSSR->setGeometry(QRect(910, 810, 41, 41));
        WestAfricanStatesUSA = new QPushButton(centralwidget);
        WestAfricanStatesUSA->setObjectName(QString::fromUtf8("WestAfricanStatesUSA"));
        WestAfricanStatesUSA->setGeometry(QRect(860, 810, 41, 41));
        AlgeriaUSA = new QPushButton(centralwidget);
        AlgeriaUSA->setObjectName(QString::fromUtf8("AlgeriaUSA"));
        AlgeriaUSA->setGeometry(QRect(980, 680, 41, 41));
        MoroccoUSSR = new QPushButton(centralwidget);
        MoroccoUSSR->setObjectName(QString::fromUtf8("MoroccoUSSR"));
        MoroccoUSSR->setGeometry(QRect(920, 710, 41, 41));
        DominicanRepUSSR = new QPushButton(centralwidget);
        DominicanRepUSSR->setObjectName(QString::fromUtf8("DominicanRepUSSR"));
        DominicanRepUSSR->setGeometry(QRect(650, 820, 41, 41));
        RomaniaUSA = new QPushButton(centralwidget);
        RomaniaUSA->setObjectName(QString::fromUtf8("RomaniaUSA"));
        RomaniaUSA->setGeometry(QRect(1320, 450, 41, 41));
        AlgeriaUSSR = new QPushButton(centralwidget);
        AlgeriaUSSR->setObjectName(QString::fromUtf8("AlgeriaUSSR"));
        AlgeriaUSSR->setGeometry(QRect(1030, 680, 41, 41));
        SaharanStatesUSA = new QPushButton(centralwidget);
        SaharanStatesUSA->setObjectName(QString::fromUtf8("SaharanStatesUSA"));
        SaharanStatesUSA->setGeometry(QRect(1030, 840, 41, 41));
        SpainPortugalUSSR = new QPushButton(centralwidget);
        SpainPortugalUSSR->setObjectName(QString::fromUtf8("SpainPortugalUSSR"));
        SpainPortugalUSSR->setGeometry(QRect(890, 570, 41, 41));
        SpainPortugalUSA = new QPushButton(centralwidget);
        SpainPortugalUSA->setObjectName(QString::fromUtf8("SpainPortugalUSA"));
        SpainPortugalUSA->setGeometry(QRect(840, 570, 41, 41));
        AustriaUSSR = new QPushButton(centralwidget);
        AustriaUSSR->setObjectName(QString::fromUtf8("AustriaUSSR"));
        AustriaUSSR->setGeometry(QRect(1150, 440, 41, 41));
        WGermanyUSSR = new QPushButton(centralwidget);
        WGermanyUSSR->setObjectName(QString::fromUtf8("WGermanyUSSR"));
        WGermanyUSSR->setGeometry(QRect(1100, 370, 41, 41));
        BeneluxUSSR = new QPushButton(centralwidget);
        BeneluxUSSR->setObjectName(QString::fromUtf8("BeneluxUSSR"));
        BeneluxUSSR->setGeometry(QRect(990, 370, 41, 41));
        WGermanyUSA = new QPushButton(centralwidget);
        WGermanyUSA->setObjectName(QString::fromUtf8("WGermanyUSA"));
        WGermanyUSA->setGeometry(QRect(1050, 370, 41, 41));
        SwedenUSSR = new QPushButton(centralwidget);
        SwedenUSSR->setObjectName(QString::fromUtf8("SwedenUSSR"));
        SwedenUSSR->setGeometry(QRect(1180, 210, 41, 41));
        SwedenUSA = new QPushButton(centralwidget);
        SwedenUSA->setObjectName(QString::fromUtf8("SwedenUSA"));
        SwedenUSA->setGeometry(QRect(1130, 210, 41, 41));
        DenmarkUSSR = new QPushButton(centralwidget);
        DenmarkUSSR->setObjectName(QString::fromUtf8("DenmarkUSSR"));
        DenmarkUSSR->setGeometry(QRect(1050, 220, 41, 41));
        DenmarkUSA = new QPushButton(centralwidget);
        DenmarkUSA->setObjectName(QString::fromUtf8("DenmarkUSA"));
        DenmarkUSA->setGeometry(QRect(1000, 220, 41, 41));
        NorwayUSSR = new QPushButton(centralwidget);
        NorwayUSSR->setObjectName(QString::fromUtf8("NorwayUSSR"));
        NorwayUSSR->setGeometry(QRect(1030, 140, 41, 41));
        FinlandUSSR = new QPushButton(centralwidget);
        FinlandUSSR->setObjectName(QString::fromUtf8("FinlandUSSR"));
        FinlandUSSR->setGeometry(QRect(1330, 140, 41, 41));
        UKUSSR = new QPushButton(centralwidget);
        UKUSSR->setObjectName(QString::fromUtf8("UKUSSR"));
        UKUSSR->setGeometry(QRect(910, 290, 41, 41));
        NorwayUSA = new QPushButton(centralwidget);
        NorwayUSA->setObjectName(QString::fromUtf8("NorwayUSA"));
        NorwayUSA->setGeometry(QRect(980, 140, 41, 41));
        IsraelUSA = new QPushButton(centralwidget);
        IsraelUSA->setObjectName(QString::fromUtf8("IsraelUSA"));
        IsraelUSA->setGeometry(QRect(1330, 690, 41, 41));
        IsraelUSSR = new QPushButton(centralwidget);
        IsraelUSSR->setObjectName(QString::fromUtf8("IsraelUSSR"));
        IsraelUSSR->setGeometry(QRect(1380, 690, 41, 41));
        UKUSA = new QPushButton(centralwidget);
        UKUSA->setObjectName(QString::fromUtf8("UKUSA"));
        UKUSA->setGeometry(QRect(860, 290, 41, 41));
        BulgariaUSSR = new QPushButton(centralwidget);
        BulgariaUSSR->setObjectName(QString::fromUtf8("BulgariaUSSR"));
        BulgariaUSSR->setGeometry(QRect(1350, 520, 41, 41));
        BulgariaUSA = new QPushButton(centralwidget);
        BulgariaUSA->setObjectName(QString::fromUtf8("BulgariaUSA"));
        BulgariaUSA->setGeometry(QRect(1300, 520, 41, 41));
        EgyptUSA = new QPushButton(centralwidget);
        EgyptUSA->setObjectName(QString::fromUtf8("EgyptUSA"));
        EgyptUSA->setGeometry(QRect(1280, 770, 41, 41));
        TurkeyUSA = new QPushButton(centralwidget);
        TurkeyUSA->setObjectName(QString::fromUtf8("TurkeyUSA"));
        TurkeyUSA->setGeometry(QRect(1410, 530, 41, 41));
        EgyptUSSR = new QPushButton(centralwidget);
        EgyptUSSR->setObjectName(QString::fromUtf8("EgyptUSSR"));
        EgyptUSSR->setGeometry(QRect(1330, 770, 41, 41));
        IraqUSSR = new QPushButton(centralwidget);
        IraqUSSR->setObjectName(QString::fromUtf8("IraqUSSR"));
        IraqUSSR->setGeometry(QRect(1510, 690, 41, 41));
        LibyaUSA = new QPushButton(centralwidget);
        LibyaUSA->setObjectName(QString::fromUtf8("LibyaUSA"));
        LibyaUSA->setGeometry(QRect(1160, 750, 41, 41));
        TurkeyUSSR = new QPushButton(centralwidget);
        TurkeyUSSR->setObjectName(QString::fromUtf8("TurkeyUSSR"));
        TurkeyUSSR->setGeometry(QRect(1460, 530, 41, 41));
        SyriaUSSR = new QPushButton(centralwidget);
        SyriaUSSR->setObjectName(QString::fromUtf8("SyriaUSSR"));
        SyriaUSSR->setGeometry(QRect(1510, 610, 41, 41));
        IraqUSA = new QPushButton(centralwidget);
        IraqUSA->setObjectName(QString::fromUtf8("IraqUSA"));
        IraqUSA->setGeometry(QRect(1460, 690, 41, 41));
        SyriaUSA = new QPushButton(centralwidget);
        SyriaUSA->setObjectName(QString::fromUtf8("SyriaUSA"));
        SyriaUSA->setGeometry(QRect(1460, 610, 41, 41));
        BeneluxUSA = new QPushButton(centralwidget);
        BeneluxUSA->setObjectName(QString::fromUtf8("BeneluxUSA"));
        BeneluxUSA->setGeometry(QRect(940, 370, 41, 41));
        FranceUSSR = new QPushButton(centralwidget);
        FranceUSSR->setObjectName(QString::fromUtf8("FranceUSSR"));
        FranceUSSR->setGeometry(QRect(970, 460, 41, 41));
        FranceUSA = new QPushButton(centralwidget);
        FranceUSA->setObjectName(QString::fromUtf8("FranceUSA"));
        FranceUSA->setGeometry(QRect(920, 460, 41, 41));
        YugoslaviaUSSR = new QPushButton(centralwidget);
        YugoslaviaUSSR->setObjectName(QString::fromUtf8("YugoslaviaUSSR"));
        YugoslaviaUSSR->setGeometry(QRect(1240, 530, 41, 41));
        ItalyUSSR = new QPushButton(centralwidget);
        ItalyUSSR->setObjectName(QString::fromUtf8("ItalyUSSR"));
        ItalyUSSR->setGeometry(QRect(1120, 520, 41, 41));
        ItalyUSA = new QPushButton(centralwidget);
        ItalyUSA->setObjectName(QString::fromUtf8("ItalyUSA"));
        ItalyUSA->setGeometry(QRect(1070, 520, 41, 41));
        YugoslaviaUSA = new QPushButton(centralwidget);
        YugoslaviaUSA->setObjectName(QString::fromUtf8("YugoslaviaUSA"));
        YugoslaviaUSA->setGeometry(QRect(1190, 530, 41, 41));
        TunisiaUSA = new QPushButton(centralwidget);
        TunisiaUSA->setObjectName(QString::fromUtf8("TunisiaUSA"));
        TunisiaUSA->setGeometry(QRect(1100, 670, 41, 41));
        TunisiaUSSR = new QPushButton(centralwidget);
        TunisiaUSSR->setObjectName(QString::fromUtf8("TunisiaUSSR"));
        TunisiaUSSR->setGeometry(QRect(1150, 670, 41, 41));
        GreeceUSSR = new QPushButton(centralwidget);
        GreeceUSSR->setObjectName(QString::fromUtf8("GreeceUSSR"));
        GreeceUSSR->setGeometry(QRect(1260, 610, 41, 41));
        CzechoslovakiaUSSR = new QPushButton(centralwidget);
        CzechoslovakiaUSSR->setObjectName(QString::fromUtf8("CzechoslovakiaUSSR"));
        CzechoslovakiaUSSR->setGeometry(QRect(1240, 370, 41, 41));
        RomaniaUSSR = new QPushButton(centralwidget);
        RomaniaUSSR->setObjectName(QString::fromUtf8("RomaniaUSSR"));
        RomaniaUSSR->setGeometry(QRect(1370, 450, 41, 41));
        PolandUSSR = new QPushButton(centralwidget);
        PolandUSSR->setObjectName(QString::fromUtf8("PolandUSSR"));
        PolandUSSR->setGeometry(QRect(1260, 290, 41, 41));
        PolandUSA = new QPushButton(centralwidget);
        PolandUSA->setObjectName(QString::fromUtf8("PolandUSA"));
        PolandUSA->setGeometry(QRect(1210, 290, 41, 41));
        GreeceUSA = new QPushButton(centralwidget);
        GreeceUSA->setObjectName(QString::fromUtf8("GreeceUSA"));
        GreeceUSA->setGeometry(QRect(1210, 610, 41, 41));
        CzechoslovakiaUSA = new QPushButton(centralwidget);
        CzechoslovakiaUSA->setObjectName(QString::fromUtf8("CzechoslovakiaUSA"));
        CzechoslovakiaUSA->setGeometry(QRect(1190, 370, 41, 41));
        graphicsView = new QGraphicsView(centralwidget);
        graphicsView->setObjectName(QString::fromUtf8("graphicsView"));
        graphicsView->setGeometry(QRect(0, 0, 2580, 1680));
        graphicsView->setStyleSheet(QString::fromUtf8("background-image: url(:/new/prefix1/Photo/background.png);\n"
""));
        CostaRicaUSA = new QPushButton(centralwidget);
        CostaRicaUSA->setObjectName(QString::fromUtf8("CostaRicaUSA"));
        CostaRicaUSA->setGeometry(QRect(250, 930, 41, 41));
        CostaRicaUSSR = new QPushButton(centralwidget);
        CostaRicaUSSR->setObjectName(QString::fromUtf8("CostaRicaUSSR"));
        CostaRicaUSSR->setGeometry(QRect(300, 930, 41, 41));
        UruguayUSSR = new QPushButton(centralwidget);
        UruguayUSSR->setObjectName(QString::fromUtf8("UruguayUSSR"));
        UruguayUSSR->setGeometry(QRect(660, 1390, 41, 41));
        UruguayUSA = new QPushButton(centralwidget);
        UruguayUSA->setObjectName(QString::fromUtf8("UruguayUSA"));
        UruguayUSA->setGeometry(QRect(610, 1390, 41, 41));
        ArgentinaUSA = new QPushButton(centralwidget);
        ArgentinaUSA->setObjectName(QString::fromUtf8("ArgentinaUSA"));
        ArgentinaUSA->setGeometry(QRect(480, 1460, 41, 41));
        ArgentinaUSSR = new QPushButton(centralwidget);
        ArgentinaUSSR->setObjectName(QString::fromUtf8("ArgentinaUSSR"));
        ArgentinaUSSR->setGeometry(QRect(530, 1460, 41, 41));
        ChileUSA = new QPushButton(centralwidget);
        ChileUSA->setObjectName(QString::fromUtf8("ChileUSA"));
        ChileUSA->setGeometry(QRect(450, 1310, 41, 41));
        ChileUSSR = new QPushButton(centralwidget);
        ChileUSSR->setObjectName(QString::fromUtf8("ChileUSSR"));
        ChileUSSR->setGeometry(QRect(500, 1310, 41, 41));
        ParaguayUSA = new QPushButton(centralwidget);
        ParaguayUSA->setObjectName(QString::fromUtf8("ParaguayUSA"));
        ParaguayUSA->setGeometry(QRect(570, 1300, 41, 41));
        ParaguayUSSR = new QPushButton(centralwidget);
        ParaguayUSSR->setObjectName(QString::fromUtf8("ParaguayUSSR"));
        ParaguayUSSR->setGeometry(QRect(620, 1300, 41, 41));
        BrazilUSA = new QPushButton(centralwidget);
        BrazilUSA->setObjectName(QString::fromUtf8("BrazilUSA"));
        BrazilUSA->setGeometry(QRect(700, 1140, 41, 41));
        BrazilUSSR = new QPushButton(centralwidget);
        BrazilUSSR->setObjectName(QString::fromUtf8("BrazilUSSR"));
        BrazilUSSR->setGeometry(QRect(750, 1140, 41, 41));
        BoliviaUSA = new QPushButton(centralwidget);
        BoliviaUSA->setObjectName(QString::fromUtf8("BoliviaUSA"));
        BoliviaUSA->setGeometry(QRect(510, 1210, 41, 41));
        BoliviaUSSR = new QPushButton(centralwidget);
        BoliviaUSSR->setObjectName(QString::fromUtf8("BoliviaUSSR"));
        BoliviaUSSR->setGeometry(QRect(560, 1210, 41, 41));
        PeruUSA = new QPushButton(centralwidget);
        PeruUSA->setObjectName(QString::fromUtf8("PeruUSA"));
        PeruUSA->setGeometry(QRect(390, 1140, 41, 41));
        PeruUSSR = new QPushButton(centralwidget);
        PeruUSSR->setObjectName(QString::fromUtf8("PeruUSSR"));
        PeruUSSR->setGeometry(QRect(440, 1140, 41, 41));
        EcuadorUSA = new QPushButton(centralwidget);
        EcuadorUSA->setObjectName(QString::fromUtf8("EcuadorUSA"));
        EcuadorUSA->setGeometry(QRect(330, 1060, 41, 41));
        SouthAfricaUSA = new QPushButton(centralwidget);
        SouthAfricaUSA->setObjectName(QString::fromUtf8("SouthAfricaUSA"));
        SouthAfricaUSA->setGeometry(QRect(1200, 1370, 41, 41));
        SouthAfricaUSSR = new QPushButton(centralwidget);
        SouthAfricaUSSR->setObjectName(QString::fromUtf8("SouthAfricaUSSR"));
        SouthAfricaUSSR->setGeometry(QRect(1250, 1370, 41, 41));
        BotswanaUSA = new QPushButton(centralwidget);
        BotswanaUSA->setObjectName(QString::fromUtf8("BotswanaUSA"));
        BotswanaUSA->setGeometry(QRect(1260, 1280, 41, 41));
        BotswanaUSSR = new QPushButton(centralwidget);
        BotswanaUSSR->setObjectName(QString::fromUtf8("BotswanaUSSR"));
        BotswanaUSSR->setGeometry(QRect(1310, 1280, 41, 41));
        ZimbabweUSA = new QPushButton(centralwidget);
        ZimbabweUSA->setObjectName(QString::fromUtf8("ZimbabweUSA"));
        ZimbabweUSA->setGeometry(QRect(1290, 1200, 41, 41));
        ZimbabweUSSR = new QPushButton(centralwidget);
        ZimbabweUSSR->setObjectName(QString::fromUtf8("ZimbabweUSSR"));
        ZimbabweUSSR->setGeometry(QRect(1340, 1200, 41, 41));
        SEAfricanStatesUSA = new QPushButton(centralwidget);
        SEAfricanStatesUSA->setObjectName(QString::fromUtf8("SEAfricanStatesUSA"));
        SEAfricanStatesUSA->setGeometry(QRect(1400, 1140, 41, 41));
        SEAfricanStatesUSSR = new QPushButton(centralwidget);
        SEAfricanStatesUSSR->setObjectName(QString::fromUtf8("SEAfricanStatesUSSR"));
        SEAfricanStatesUSSR->setGeometry(QRect(1450, 1140, 41, 41));
        ZaireUSA = new QPushButton(centralwidget);
        ZaireUSA->setObjectName(QString::fromUtf8("ZaireUSA"));
        ZaireUSA->setGeometry(QRect(1250, 1070, 41, 41));
        ZaireUSSR = new QPushButton(centralwidget);
        ZaireUSSR->setObjectName(QString::fromUtf8("ZaireUSSR"));
        ZaireUSSR->setGeometry(QRect(1300, 1070, 41, 41));
        AngolaUSA = new QPushButton(centralwidget);
        AngolaUSA->setObjectName(QString::fromUtf8("AngolaUSA"));
        AngolaUSA->setGeometry(QRect(1160, 1160, 41, 41));
        AngolaUSSR = new QPushButton(centralwidget);
        AngolaUSSR->setObjectName(QString::fromUtf8("AngolaUSSR"));
        AngolaUSSR->setGeometry(QRect(1210, 1160, 41, 41));
        KenyaUSA = new QPushButton(centralwidget);
        KenyaUSA->setObjectName(QString::fromUtf8("KenyaUSA"));
        KenyaUSA->setGeometry(QRect(1390, 1040, 41, 41));
        KenyaUSSR = new QPushButton(centralwidget);
        KenyaUSSR->setObjectName(QString::fromUtf8("KenyaUSSR"));
        KenyaUSSR->setGeometry(QRect(1440, 1040, 41, 41));
        CameroonUSA = new QPushButton(centralwidget);
        CameroonUSA->setObjectName(QString::fromUtf8("CameroonUSA"));
        CameroonUSA->setGeometry(QRect(1120, 1030, 41, 41));
        CameroonUSSR = new QPushButton(centralwidget);
        CameroonUSSR->setObjectName(QString::fromUtf8("CameroonUSSR"));
        CameroonUSSR->setGeometry(QRect(1170, 1030, 41, 41));
        SomaliaUSA = new QPushButton(centralwidget);
        SomaliaUSA->setObjectName(QString::fromUtf8("SomaliaUSA"));
        SomaliaUSA->setGeometry(QRect(1500, 970, 41, 41));
        SomaliaUSSR = new QPushButton(centralwidget);
        SomaliaUSSR->setObjectName(QString::fromUtf8("SomaliaUSSR"));
        SomaliaUSSR->setGeometry(QRect(1550, 970, 41, 41));
        SudanUSA = new QPushButton(centralwidget);
        SudanUSA->setObjectName(QString::fromUtf8("SudanUSA"));
        SudanUSA->setGeometry(QRect(1300, 860, 41, 41));
        SudanUSSR = new QPushButton(centralwidget);
        SudanUSSR->setObjectName(QString::fromUtf8("SudanUSSR"));
        SudanUSSR->setGeometry(QRect(1350, 860, 41, 41));
        SaudiArabiaUSA = new QPushButton(centralwidget);
        SaudiArabiaUSA->setObjectName(QString::fromUtf8("SaudiArabiaUSA"));
        SaudiArabiaUSA->setGeometry(QRect(1500, 840, 41, 41));
        JordanUSA = new QPushButton(centralwidget);
        JordanUSA->setObjectName(QString::fromUtf8("JordanUSA"));
        JordanUSA->setGeometry(QRect(1400, 770, 41, 41));
        SaudiArabiaUSSR = new QPushButton(centralwidget);
        SaudiArabiaUSSR->setObjectName(QString::fromUtf8("SaudiArabiaUSSR"));
        SaudiArabiaUSSR->setGeometry(QRect(1550, 840, 41, 41));
        EthiopiaUSSR = new QPushButton(centralwidget);
        EthiopiaUSSR->setObjectName(QString::fromUtf8("EthiopiaUSSR"));
        EthiopiaUSSR->setGeometry(QRect(1430, 940, 41, 41));
        EthiopiaUSA = new QPushButton(centralwidget);
        EthiopiaUSA->setObjectName(QString::fromUtf8("EthiopiaUSA"));
        EthiopiaUSA->setGeometry(QRect(1380, 940, 41, 41));
        AustraliaUSA = new QPushButton(centralwidget);
        AustraliaUSA->setObjectName(QString::fromUtf8("AustraliaUSA"));
        AustraliaUSA->setGeometry(QRect(2260, 1240, 41, 41));
        AustraliaUSSR = new QPushButton(centralwidget);
        AustraliaUSSR->setObjectName(QString::fromUtf8("AustraliaUSSR"));
        AustraliaUSSR->setGeometry(QRect(2310, 1240, 41, 41));
        IndonesiaUSA = new QPushButton(centralwidget);
        IndonesiaUSA->setObjectName(QString::fromUtf8("IndonesiaUSA"));
        IndonesiaUSA->setGeometry(QRect(2260, 1110, 41, 41));
        IndonesiaUSSR = new QPushButton(centralwidget);
        IndonesiaUSSR->setObjectName(QString::fromUtf8("IndonesiaUSSR"));
        IndonesiaUSSR->setGeometry(QRect(2310, 1110, 41, 41));
        MalaysiaUSA = new QPushButton(centralwidget);
        MalaysiaUSA->setObjectName(QString::fromUtf8("MalaysiaUSA"));
        MalaysiaUSA->setGeometry(QRect(2080, 1010, 41, 41));
        MalaysiaUSSR = new QPushButton(centralwidget);
        MalaysiaUSSR->setObjectName(QString::fromUtf8("MalaysiaUSSR"));
        MalaysiaUSSR->setGeometry(QRect(2130, 1010, 41, 41));
        BurmaUSA = new QPushButton(centralwidget);
        BurmaUSA->setObjectName(QString::fromUtf8("BurmaUSA"));
        BurmaUSA->setGeometry(QRect(1960, 800, 41, 41));
        VietnamUSA = new QPushButton(centralwidget);
        VietnamUSA->setObjectName(QString::fromUtf8("VietnamUSA"));
        VietnamUSA->setGeometry(QRect(2140, 890, 41, 41));
        BurmaUSSR = new QPushButton(centralwidget);
        BurmaUSSR->setObjectName(QString::fromUtf8("BurmaUSSR"));
        BurmaUSSR->setGeometry(QRect(2010, 800, 41, 41));
        VietnamUSSR = new QPushButton(centralwidget);
        VietnamUSSR->setObjectName(QString::fromUtf8("VietnamUSSR"));
        VietnamUSSR->setGeometry(QRect(2190, 890, 41, 41));
        ThailandUSA = new QPushButton(centralwidget);
        ThailandUSA->setObjectName(QString::fromUtf8("ThailandUSA"));
        ThailandUSA->setGeometry(QRect(2020, 890, 41, 41));
        ThailandUSSR = new QPushButton(centralwidget);
        ThailandUSSR->setObjectName(QString::fromUtf8("ThailandUSSR"));
        ThailandUSSR->setGeometry(QRect(2070, 890, 41, 41));
        PhilippinesUSA = new QPushButton(centralwidget);
        PhilippinesUSA->setObjectName(QString::fromUtf8("PhilippinesUSA"));
        PhilippinesUSA->setGeometry(QRect(2300, 890, 41, 41));
        PhilippinesUSSR = new QPushButton(centralwidget);
        PhilippinesUSSR->setObjectName(QString::fromUtf8("PhilippinesUSSR"));
        PhilippinesUSSR->setGeometry(QRect(2350, 890, 41, 41));
        TaiwanChinaUSA = new QPushButton(centralwidget);
        TaiwanChinaUSA->setObjectName(QString::fromUtf8("TaiwanChinaUSA"));
        TaiwanChinaUSA->setGeometry(QRect(2250, 770, 41, 41));
        TaiwanChinaUSSR = new QPushButton(centralwidget);
        TaiwanChinaUSSR->setObjectName(QString::fromUtf8("TaiwanChinaUSSR"));
        TaiwanChinaUSSR->setGeometry(QRect(2300, 770, 41, 41));
        LaosCambodiaUSA = new QPushButton(centralwidget);
        LaosCambodiaUSA->setObjectName(QString::fromUtf8("LaosCambodiaUSA"));
        LaosCambodiaUSA->setGeometry(QRect(2070, 810, 41, 41));
        LaosCambodiaUSSR = new QPushButton(centralwidget);
        LaosCambodiaUSSR->setObjectName(QString::fromUtf8("LaosCambodiaUSSR"));
        LaosCambodiaUSSR->setGeometry(QRect(2120, 810, 41, 41));
        JapanUSA = new QPushButton(centralwidget);
        JapanUSA->setObjectName(QString::fromUtf8("JapanUSA"));
        JapanUSA->setGeometry(QRect(2390, 680, 41, 41));
        JapanUSSR = new QPushButton(centralwidget);
        JapanUSSR->setObjectName(QString::fromUtf8("JapanUSSR"));
        JapanUSSR->setGeometry(QRect(2440, 680, 41, 41));
        ChinaUSA = new QPushButton(centralwidget);
        ChinaUSA->setObjectName(QString::fromUtf8("ChinaUSA"));
        ChinaUSA->setGeometry(QRect(2140, 640, 41, 41));
        ChinaUSSR = new QPushButton(centralwidget);
        ChinaUSSR->setObjectName(QString::fromUtf8("ChinaUSSR"));
        ChinaUSSR->setGeometry(QRect(2190, 640, 41, 41));
        SKoreaUSA = new QPushButton(centralwidget);
        SKoreaUSA->setObjectName(QString::fromUtf8("SKoreaUSA"));
        SKoreaUSA->setGeometry(QRect(2300, 610, 41, 41));
        SKoreaUSSR = new QPushButton(centralwidget);
        SKoreaUSSR->setObjectName(QString::fromUtf8("SKoreaUSSR"));
        SKoreaUSSR->setGeometry(QRect(2350, 610, 41, 41));
        IndiaUSSR = new QPushButton(centralwidget);
        IndiaUSSR->setObjectName(QString::fromUtf8("IndiaUSSR"));
        IndiaUSSR->setGeometry(QRect(1870, 790, 41, 41));
        PakistanUSSR = new QPushButton(centralwidget);
        PakistanUSSR->setObjectName(QString::fromUtf8("PakistanUSSR"));
        PakistanUSSR->setGeometry(QRect(1750, 740, 41, 41));
        JordanUSSR = new QPushButton(centralwidget);
        JordanUSSR->setObjectName(QString::fromUtf8("JordanUSSR"));
        JordanUSSR->setGeometry(QRect(1450, 770, 41, 41));
        PakistanUSA = new QPushButton(centralwidget);
        PakistanUSA->setObjectName(QString::fromUtf8("PakistanUSA"));
        PakistanUSA->setGeometry(QRect(1700, 740, 41, 41));
        GulfStatesUSA = new QPushButton(centralwidget);
        GulfStatesUSA->setObjectName(QString::fromUtf8("GulfStatesUSA"));
        GulfStatesUSA->setGeometry(QRect(1530, 760, 41, 41));
        IndiaUSA = new QPushButton(centralwidget);
        IndiaUSA->setObjectName(QString::fromUtf8("IndiaUSA"));
        IndiaUSA->setGeometry(QRect(1820, 790, 41, 41));
        IranUSA = new QPushButton(centralwidget);
        IranUSA->setObjectName(QString::fromUtf8("IranUSA"));
        IranUSA->setGeometry(QRect(1570, 690, 41, 41));
        AfghanistanUSA = new QPushButton(centralwidget);
        AfghanistanUSA->setObjectName(QString::fromUtf8("AfghanistanUSA"));
        AfghanistanUSA->setGeometry(QRect(1700, 640, 41, 41));
        IranUSSR = new QPushButton(centralwidget);
        IranUSSR->setObjectName(QString::fromUtf8("IranUSSR"));
        IranUSSR->setGeometry(QRect(1620, 690, 41, 41));
        GulfStatesUSSR = new QPushButton(centralwidget);
        GulfStatesUSSR->setObjectName(QString::fromUtf8("GulfStatesUSSR"));
        GulfStatesUSSR->setGeometry(QRect(1580, 760, 41, 41));
        AfghanistanUSSR = new QPushButton(centralwidget);
        AfghanistanUSSR->setObjectName(QString::fromUtf8("AfghanistanUSSR"));
        AfghanistanUSSR->setGeometry(QRect(1750, 640, 41, 41));
        NKoreaUSSR = new QPushButton(centralwidget);
        NKoreaUSSR->setObjectName(QString::fromUtf8("NKoreaUSSR"));
        NKoreaUSSR->setGeometry(QRect(2330, 530, 41, 41));
        NKoreaUSA = new QPushButton(centralwidget);
        NKoreaUSA->setObjectName(QString::fromUtf8("NKoreaUSA"));
        NKoreaUSA->setGeometry(QRect(2280, 530, 41, 41));
        EcuadorUSSR = new QPushButton(centralwidget);
        EcuadorUSSR->setObjectName(QString::fromUtf8("EcuadorUSSR"));
        EcuadorUSSR->setGeometry(QRect(380, 1060, 41, 41));
        PanamaUSA = new QPushButton(centralwidget);
        PanamaUSA->setObjectName(QString::fromUtf8("PanamaUSA"));
        PanamaUSA->setGeometry(QRect(370, 930, 41, 41));
        VenezuelaUSSR = new QPushButton(centralwidget);
        VenezuelaUSSR->setObjectName(QString::fromUtf8("VenezuelaUSSR"));
        VenezuelaUSSR->setGeometry(QRect(560, 940, 41, 41));
        PanamaUSSR = new QPushButton(centralwidget);
        PanamaUSSR->setObjectName(QString::fromUtf8("PanamaUSSR"));
        PanamaUSSR->setGeometry(QRect(420, 930, 41, 41));
        VenezuelaUSA = new QPushButton(centralwidget);
        VenezuelaUSA->setObjectName(QString::fromUtf8("VenezuelaUSA"));
        VenezuelaUSA->setGeometry(QRect(510, 940, 41, 41));
        ColombiaUSA = new QPushButton(centralwidget);
        ColombiaUSA->setObjectName(QString::fromUtf8("ColombiaUSA"));
        ColombiaUSA->setGeometry(QRect(440, 1020, 41, 41));
        ColombiaUSSR = new QPushButton(centralwidget);
        ColombiaUSSR->setObjectName(QString::fromUtf8("ColombiaUSSR"));
        ColombiaUSSR->setGeometry(QRect(490, 1020, 41, 41));
        verticalLayoutWidget = new QWidget(centralwidget);
        verticalLayoutWidget->setObjectName(QString::fromUtf8("verticalLayoutWidget"));
        verticalLayoutWidget->setGeometry(QRect(40, 50, 741, 291));
        Resource_point = new QVBoxLayout(verticalLayoutWidget);
        Resource_point->setObjectName(QString::fromUtf8("Resource_point"));
        Resource_point->setContentsMargins(0, 0, 0, 0);
        USA_resource = new QTextBrowser(verticalLayoutWidget);
        USA_resource->setObjectName(QString::fromUtf8("USA_resource"));
        USA_resource->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/Photo/White background.png);"));

        Resource_point->addWidget(USA_resource);

        USSR_resource = new QTextBrowser(verticalLayoutWidget);
        USSR_resource->setObjectName(QString::fromUtf8("USSR_resource"));
        USSR_resource->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/Photo/White background.png);"));

        Resource_point->addWidget(USSR_resource);

        btn_next = new QPushButton(centralwidget);
        btn_next->setObjectName(QString::fromUtf8("btn_next"));
        btn_next->setGeometry(QRect(110, 1400, 211, 91));
        QFont font;
        font.setFamily(QString::fromUtf8("Comic Sans MS"));
        font.setPointSize(16);
        btn_next->setFont(font);
        btn_next->setStyleSheet(QString::fromUtf8("border-image: url(:/new/prefix1/Photo/White background.png);"));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/Icons/Photo/next.png"), QSize(), QIcon::Normal, QIcon::Off);
        btn_next->setIcon(icon);
        btn_next->setIconSize(QSize(60, 60));
        curr_player_display = new QTextBrowser(centralwidget);
        curr_player_display->setObjectName(QString::fromUtf8("curr_player_display"));
        curr_player_display->setGeometry(QRect(930, 1460, 191, 71));
        curr_player_display->setStyleSheet(QString::fromUtf8("background-image: url(:/new/prefix1/Photo/Empty background.png);"));
        curr_player_head = new QTextBrowser(centralwidget);
        curr_player_head->setObjectName(QString::fromUtf8("curr_player_head"));
        curr_player_head->setGeometry(QRect(830, 1360, 351, 91));
        curr_player_head->setStyleSheet(QString::fromUtf8("background-image: url(:/new/prefix1/Photo/Empty background.png);"));
        btn_coup = new QPushButton(centralwidget);
        btn_coup->setObjectName(QString::fromUtf8("btn_coup"));
        btn_coup->setGeometry(QRect(80, 1090, 201, 91));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Arial"));
        font1.setPointSize(12);
        btn_coup->setFont(font1);
        round1 = new QLabel(centralwidget);
        round1->setObjectName(QString::fromUtf8("round1"));
        round1->setGeometry(QRect(2000, 240, 61, 61));
        round1->setStyleSheet(QString::fromUtf8("image: url(:/new/prefix1/Photo/round1_.png);"));
        round2 = new QLabel(centralwidget);
        round2->setObjectName(QString::fromUtf8("round2"));
        round2->setGeometry(QRect(2060, 240, 61, 61));
        round2->setStyleSheet(QString::fromUtf8("image: url(:/new/prefix1/Photo/round2_.png);"));
        round4 = new QLabel(centralwidget);
        round4->setObjectName(QString::fromUtf8("round4"));
        round4->setGeometry(QRect(2190, 240, 61, 61));
        round4->setStyleSheet(QString::fromUtf8("image: url(:/new/prefix1/Photo/round4_.png);"));
        round3 = new QLabel(centralwidget);
        round3->setObjectName(QString::fromUtf8("round3"));
        round3->setGeometry(QRect(2130, 240, 61, 61));
        round3->setStyleSheet(QString::fromUtf8("image: url(:/new/prefix1/Photo/round3_.png);"));
        round5 = new QLabel(centralwidget);
        round5->setObjectName(QString::fromUtf8("round5"));
        round5->setGeometry(QRect(2260, 240, 61, 61));
        round5->setStyleSheet(QString::fromUtf8("image: url(:/new/prefix1/Photo/round5_.png);"));
        round6 = new QLabel(centralwidget);
        round6->setObjectName(QString::fromUtf8("round6"));
        round6->setGeometry(QRect(2320, 240, 61, 61));
        round6->setStyleSheet(QString::fromUtf8("image: url(:/new/prefix1/Photo/round6_.png);"));
        round7 = new QLabel(centralwidget);
        round7->setObjectName(QString::fromUtf8("round7"));
        round7->setGeometry(QRect(2390, 240, 61, 61));
        round7->setStyleSheet(QString::fromUtf8("image: url(:/new/prefix1/Photo/round7_.png);"));
        turn1 = new QLabel(centralwidget);
        turn1->setObjectName(QString::fromUtf8("turn1"));
        turn1->setGeometry(QRect(1840, 90, 61, 71));
        turn1->setStyleSheet(QString::fromUtf8("image: url(:/new/prefix1/Photo/turn1_.png);"));
        turn2 = new QLabel(centralwidget);
        turn2->setObjectName(QString::fromUtf8("turn2"));
        turn2->setGeometry(QRect(1910, 90, 61, 71));
        turn2->setStyleSheet(QString::fromUtf8("image: url(:/new/prefix1/Photo/turn2_.png);"));
        turn3 = new QLabel(centralwidget);
        turn3->setObjectName(QString::fromUtf8("turn3"));
        turn3->setGeometry(QRect(1980, 90, 61, 71));
        turn3->setStyleSheet(QString::fromUtf8("image: url(:/new/prefix1/Photo/turn3_.png);"));
        turn4 = new QLabel(centralwidget);
        turn4->setObjectName(QString::fromUtf8("turn4"));
        turn4->setGeometry(QRect(2041, 90, 61, 71));
        turn4->setStyleSheet(QString::fromUtf8("image: url(:/new/prefix1/Photo/turn4_.png);"));
        turn5 = new QLabel(centralwidget);
        turn5->setObjectName(QString::fromUtf8("turn5"));
        turn5->setGeometry(QRect(2110, 94, 61, 71));
        turn5->setStyleSheet(QString::fromUtf8("image: url(:/new/prefix1/Photo/turn5_.png);"));
        turn6 = new QLabel(centralwidget);
        turn6->setObjectName(QString::fromUtf8("turn6"));
        turn6->setGeometry(QRect(2180, 94, 61, 71));
        turn6->setStyleSheet(QString::fromUtf8("image: url(:/new/prefix1/Photo/turn6_.png);"));
        turn7 = new QLabel(centralwidget);
        turn7->setObjectName(QString::fromUtf8("turn7"));
        turn7->setGeometry(QRect(2251, 94, 61, 71));
        turn7->setStyleSheet(QString::fromUtf8("image: url(:/new/prefix1/Photo/turn7_.png);"));
        turn8 = new QLabel(centralwidget);
        turn8->setObjectName(QString::fromUtf8("turn8"));
        turn8->setGeometry(QRect(2311, 94, 61, 71));
        turn8->setStyleSheet(QString::fromUtf8("image: url(:/new/prefix1/Photo/turn8_.png);"));
        turn9 = new QLabel(centralwidget);
        turn9->setObjectName(QString::fromUtf8("turn9"));
        turn9->setGeometry(QRect(2380, 90, 61, 71));
        turn9->setStyleSheet(QString::fromUtf8("image: url(:/new/prefix1/Photo/turn9_.png);"));
        turn10 = new QLabel(centralwidget);
        turn10->setObjectName(QString::fromUtf8("turn10"));
        turn10->setGeometry(QRect(2450, 94, 61, 71));
        turn10->setStyleSheet(QString::fromUtf8("image: url(:/new/prefix1/Photo/turn10_.png);"));
        defcon5 = new QLabel(centralwidget);
        defcon5->setObjectName(QString::fromUtf8("defcon5"));
        defcon5->setGeometry(QRect(50, 1270, 61, 61));
        defcon5->setStyleSheet(QString::fromUtf8("image: url(:/new/prefix1/Photo/defcon5_.png);"));
        defcon4 = new QLabel(centralwidget);
        defcon4->setObjectName(QString::fromUtf8("defcon4"));
        defcon4->setGeometry(QRect(121, 1274, 61, 61));
        defcon4->setStyleSheet(QString::fromUtf8("image: url(:/new/prefix1/Photo/defcon4_.png);"));
        defcon3 = new QLabel(centralwidget);
        defcon3->setObjectName(QString::fromUtf8("defcon3"));
        defcon3->setGeometry(QRect(180, 1270, 61, 61));
        defcon3->setStyleSheet(QString::fromUtf8("image: url(:/new/prefix1/Photo/defcon3_.png);"));
        defcon2 = new QLabel(centralwidget);
        defcon2->setObjectName(QString::fromUtf8("defcon2"));
        defcon2->setGeometry(QRect(251, 1274, 61, 61));
        defcon2->setStyleSheet(QString::fromUtf8("image: url(:/new/prefix1/Photo/defcon2_.png);"));
        defcon1 = new QLabel(centralwidget);
        defcon1->setObjectName(QString::fromUtf8("defcon1"));
        defcon1->setGeometry(QRect(320, 1274, 61, 61));
        defcon1->setStyleSheet(QString::fromUtf8("image: url(:/new/prefix1/Photo/defcon1_.png);"));
        MainWindow->setCentralWidget(centralwidget);
        graphicsView->raise();
        CubaUSSR->raise();
        NicaraguaUSA->raise();
        NicaraguaUSSR->raise();
        HaitiUSA->raise();
        HaitiUSSR->raise();
        DominicanRepUSA->raise();
        MoroccoUSA->raise();
        IvoryCoastUSA->raise();
        NigeriaUSA->raise();
        NigeriaUSSR->raise();
        IvoryCoastUSSR->raise();
        MexicoUSA->raise();
        CubaUSA->raise();
        MexicoUSSR->raise();
        GuatemalaUSA->raise();
        GuatemalaUSSR->raise();
        HondurasUSA->raise();
        ElSalvadorUSSR->raise();
        HondurasUSSR->raise();
        ElSalvadorUSA->raise();
        LibyaUSSR->raise();
        LebanonUSSR->raise();
        CanadaUSA->raise();
        EGermanyUSSR->raise();
        EGermanyUSA->raise();
        CanadaUSSR->raise();
        FinlandUSA->raise();
        HungaryUSA->raise();
        HungaryUSSR->raise();
        LebanonUSA->raise();
        AustriaUSA->raise();
        SaharanStatesUSSR->raise();
        WestAfricanStatesUSSR->raise();
        WestAfricanStatesUSA->raise();
        AlgeriaUSA->raise();
        MoroccoUSSR->raise();
        DominicanRepUSSR->raise();
        RomaniaUSA->raise();
        AlgeriaUSSR->raise();
        SaharanStatesUSA->raise();
        SpainPortugalUSSR->raise();
        SpainPortugalUSA->raise();
        AustriaUSSR->raise();
        WGermanyUSSR->raise();
        BeneluxUSSR->raise();
        WGermanyUSA->raise();
        SwedenUSSR->raise();
        SwedenUSA->raise();
        DenmarkUSSR->raise();
        DenmarkUSA->raise();
        NorwayUSSR->raise();
        FinlandUSSR->raise();
        UKUSSR->raise();
        NorwayUSA->raise();
        IsraelUSA->raise();
        IsraelUSSR->raise();
        UKUSA->raise();
        BulgariaUSSR->raise();
        BulgariaUSA->raise();
        EgyptUSA->raise();
        TurkeyUSA->raise();
        EgyptUSSR->raise();
        IraqUSSR->raise();
        LibyaUSA->raise();
        TurkeyUSSR->raise();
        SyriaUSSR->raise();
        IraqUSA->raise();
        SyriaUSA->raise();
        BeneluxUSA->raise();
        FranceUSSR->raise();
        FranceUSA->raise();
        YugoslaviaUSSR->raise();
        ItalyUSSR->raise();
        ItalyUSA->raise();
        YugoslaviaUSA->raise();
        TunisiaUSA->raise();
        TunisiaUSSR->raise();
        GreeceUSSR->raise();
        CzechoslovakiaUSSR->raise();
        RomaniaUSSR->raise();
        PolandUSSR->raise();
        PolandUSA->raise();
        GreeceUSA->raise();
        CzechoslovakiaUSA->raise();
        CostaRicaUSA->raise();
        CostaRicaUSSR->raise();
        UruguayUSSR->raise();
        UruguayUSA->raise();
        ArgentinaUSA->raise();
        ArgentinaUSSR->raise();
        ChileUSA->raise();
        ChileUSSR->raise();
        ParaguayUSA->raise();
        ParaguayUSSR->raise();
        BrazilUSA->raise();
        BrazilUSSR->raise();
        BoliviaUSA->raise();
        BoliviaUSSR->raise();
        PeruUSA->raise();
        PeruUSSR->raise();
        EcuadorUSA->raise();
        SouthAfricaUSA->raise();
        SouthAfricaUSSR->raise();
        BotswanaUSA->raise();
        BotswanaUSSR->raise();
        ZimbabweUSA->raise();
        ZimbabweUSSR->raise();
        SEAfricanStatesUSA->raise();
        SEAfricanStatesUSSR->raise();
        ZaireUSA->raise();
        ZaireUSSR->raise();
        AngolaUSA->raise();
        AngolaUSSR->raise();
        KenyaUSA->raise();
        KenyaUSSR->raise();
        CameroonUSA->raise();
        CameroonUSSR->raise();
        SomaliaUSA->raise();
        SomaliaUSSR->raise();
        SudanUSA->raise();
        SudanUSSR->raise();
        SaudiArabiaUSA->raise();
        JordanUSA->raise();
        SaudiArabiaUSSR->raise();
        EthiopiaUSSR->raise();
        EthiopiaUSA->raise();
        AustraliaUSA->raise();
        AustraliaUSSR->raise();
        IndonesiaUSA->raise();
        IndonesiaUSSR->raise();
        MalaysiaUSA->raise();
        MalaysiaUSSR->raise();
        BurmaUSA->raise();
        VietnamUSA->raise();
        BurmaUSSR->raise();
        VietnamUSSR->raise();
        ThailandUSA->raise();
        ThailandUSSR->raise();
        PhilippinesUSA->raise();
        PhilippinesUSSR->raise();
        TaiwanChinaUSA->raise();
        TaiwanChinaUSSR->raise();
        LaosCambodiaUSA->raise();
        LaosCambodiaUSSR->raise();
        JapanUSA->raise();
        JapanUSSR->raise();
        ChinaUSA->raise();
        ChinaUSSR->raise();
        SKoreaUSA->raise();
        SKoreaUSSR->raise();
        IndiaUSSR->raise();
        PakistanUSSR->raise();
        JordanUSSR->raise();
        PakistanUSA->raise();
        GulfStatesUSA->raise();
        IndiaUSA->raise();
        IranUSA->raise();
        AfghanistanUSA->raise();
        IranUSSR->raise();
        GulfStatesUSSR->raise();
        AfghanistanUSSR->raise();
        NKoreaUSSR->raise();
        NKoreaUSA->raise();
        EcuadorUSSR->raise();
        PanamaUSA->raise();
        VenezuelaUSSR->raise();
        PanamaUSSR->raise();
        VenezuelaUSA->raise();
        ColombiaUSA->raise();
        ColombiaUSSR->raise();
        verticalLayoutWidget->raise();
        btn_next->raise();
        curr_player_display->raise();
        curr_player_head->raise();
        btn_coup->raise();
        round1->raise();
        round2->raise();
        round4->raise();
        round3->raise();
        round5->raise();
        round6->raise();
        round7->raise();
        turn1->raise();
        turn2->raise();
        turn3->raise();
        turn4->raise();
        turn5->raise();
        turn6->raise();
        turn7->raise();
        turn8->raise();
        turn9->raise();
        turn10->raise();
        defcon5->raise();
        defcon4->raise();
        defcon3->raise();
        defcon2->raise();
        defcon1->raise();
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 2580, 26));
        menuTwlight_Struggle_Lite = new QMenu(menubar);
        menuTwlight_Struggle_Lite->setObjectName(QString::fromUtf8("menuTwlight_Struggle_Lite"));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        menubar->addAction(menuTwlight_Struggle_Lite->menuAction());

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        CubaUSSR->setText(QString());
        NicaraguaUSA->setText(QString());
        NicaraguaUSSR->setText(QString());
        HaitiUSA->setText(QString());
        HaitiUSSR->setText(QString());
        DominicanRepUSA->setText(QString());
        MoroccoUSA->setText(QString());
        IvoryCoastUSA->setText(QString());
        NigeriaUSA->setText(QString());
        NigeriaUSSR->setText(QString());
        IvoryCoastUSSR->setText(QString());
        MexicoUSA->setText(QString());
        CubaUSA->setText(QString());
        MexicoUSSR->setText(QString());
        GuatemalaUSA->setText(QString());
        GuatemalaUSSR->setText(QString());
        HondurasUSA->setText(QString());
        ElSalvadorUSSR->setText(QString());
        HondurasUSSR->setText(QString());
        ElSalvadorUSA->setText(QString());
        LibyaUSSR->setText(QString());
        LebanonUSSR->setText(QString());
        CanadaUSA->setText(QString());
        EGermanyUSSR->setText(QString());
        EGermanyUSA->setText(QString());
        CanadaUSSR->setText(QString());
        FinlandUSA->setText(QString());
        HungaryUSA->setText(QString());
        HungaryUSSR->setText(QString());
        LebanonUSA->setText(QString());
        AustriaUSA->setText(QString());
        SaharanStatesUSSR->setText(QString());
        WestAfricanStatesUSSR->setText(QString());
        WestAfricanStatesUSA->setText(QString());
        AlgeriaUSA->setText(QString());
        MoroccoUSSR->setText(QString());
        DominicanRepUSSR->setText(QString());
        RomaniaUSA->setText(QString());
        AlgeriaUSSR->setText(QString());
        SaharanStatesUSA->setText(QString());
        SpainPortugalUSSR->setText(QString());
        SpainPortugalUSA->setText(QString());
        AustriaUSSR->setText(QString());
        WGermanyUSSR->setText(QString());
        BeneluxUSSR->setText(QString());
        WGermanyUSA->setText(QString());
        SwedenUSSR->setText(QString());
        SwedenUSA->setText(QString());
        DenmarkUSSR->setText(QString());
        DenmarkUSA->setText(QString());
        NorwayUSSR->setText(QString());
        FinlandUSSR->setText(QString());
        UKUSSR->setText(QString());
        NorwayUSA->setText(QString());
        IsraelUSA->setText(QString());
        IsraelUSSR->setText(QString());
        UKUSA->setText(QString());
        BulgariaUSSR->setText(QString());
        BulgariaUSA->setText(QString());
        EgyptUSA->setText(QString());
        TurkeyUSA->setText(QString());
        EgyptUSSR->setText(QString());
        IraqUSSR->setText(QString());
        LibyaUSA->setText(QString());
        TurkeyUSSR->setText(QString());
        SyriaUSSR->setText(QString());
        IraqUSA->setText(QString());
        SyriaUSA->setText(QString());
        BeneluxUSA->setText(QString());
        FranceUSSR->setText(QString());
        FranceUSA->setText(QString());
        YugoslaviaUSSR->setText(QString());
        ItalyUSSR->setText(QString());
        ItalyUSA->setText(QString());
        YugoslaviaUSA->setText(QString());
        TunisiaUSA->setText(QString());
        TunisiaUSSR->setText(QString());
        GreeceUSSR->setText(QString());
        CzechoslovakiaUSSR->setText(QString());
        RomaniaUSSR->setText(QString());
        PolandUSSR->setText(QString());
        PolandUSA->setText(QString());
        GreeceUSA->setText(QString());
        CzechoslovakiaUSA->setText(QString());
        CostaRicaUSA->setText(QString());
        CostaRicaUSSR->setText(QString());
        UruguayUSSR->setText(QString());
        UruguayUSA->setText(QString());
        ArgentinaUSA->setText(QString());
        ArgentinaUSSR->setText(QString());
        ChileUSA->setText(QString());
        ChileUSSR->setText(QString());
        ParaguayUSA->setText(QString());
        ParaguayUSSR->setText(QString());
        BrazilUSA->setText(QString());
        BrazilUSSR->setText(QString());
        BoliviaUSA->setText(QString());
        BoliviaUSSR->setText(QString());
        PeruUSA->setText(QString());
        PeruUSSR->setText(QString());
        EcuadorUSA->setText(QString());
        SouthAfricaUSA->setText(QString());
        SouthAfricaUSSR->setText(QString());
        BotswanaUSA->setText(QString());
        BotswanaUSSR->setText(QString());
        ZimbabweUSA->setText(QString());
        ZimbabweUSSR->setText(QString());
        SEAfricanStatesUSA->setText(QString());
        SEAfricanStatesUSSR->setText(QString());
        ZaireUSA->setText(QString());
        ZaireUSSR->setText(QString());
        AngolaUSA->setText(QString());
        AngolaUSSR->setText(QString());
        KenyaUSA->setText(QString());
        KenyaUSSR->setText(QString());
        CameroonUSA->setText(QString());
        CameroonUSSR->setText(QString());
        SomaliaUSA->setText(QString());
        SomaliaUSSR->setText(QString());
        SudanUSA->setText(QString());
        SudanUSSR->setText(QString());
        SaudiArabiaUSA->setText(QString());
        JordanUSA->setText(QString());
        SaudiArabiaUSSR->setText(QString());
        EthiopiaUSSR->setText(QString());
        EthiopiaUSA->setText(QString());
        AustraliaUSA->setText(QString());
        AustraliaUSSR->setText(QString());
        IndonesiaUSA->setText(QString());
        IndonesiaUSSR->setText(QString());
        MalaysiaUSA->setText(QString());
        MalaysiaUSSR->setText(QString());
        BurmaUSA->setText(QString());
        VietnamUSA->setText(QString());
        BurmaUSSR->setText(QString());
        VietnamUSSR->setText(QString());
        ThailandUSA->setText(QString());
        ThailandUSSR->setText(QString());
        PhilippinesUSA->setText(QString());
        PhilippinesUSSR->setText(QString());
        TaiwanChinaUSA->setText(QString());
        TaiwanChinaUSSR->setText(QString());
        LaosCambodiaUSA->setText(QString());
        LaosCambodiaUSSR->setText(QString());
        JapanUSA->setText(QString());
        JapanUSSR->setText(QString());
        ChinaUSA->setText(QString());
        ChinaUSSR->setText(QString());
        SKoreaUSA->setText(QString());
        SKoreaUSSR->setText(QString());
        IndiaUSSR->setText(QString());
        PakistanUSSR->setText(QString());
        JordanUSSR->setText(QString());
        PakistanUSA->setText(QString());
        GulfStatesUSA->setText(QString());
        IndiaUSA->setText(QString());
        IranUSA->setText(QString());
        AfghanistanUSA->setText(QString());
        IranUSSR->setText(QString());
        GulfStatesUSSR->setText(QString());
        AfghanistanUSSR->setText(QString());
        NKoreaUSSR->setText(QString());
        NKoreaUSA->setText(QString());
        EcuadorUSSR->setText(QString());
        PanamaUSA->setText(QString());
        VenezuelaUSSR->setText(QString());
        PanamaUSSR->setText(QString());
        VenezuelaUSA->setText(QString());
        ColombiaUSA->setText(QString());
        ColombiaUSSR->setText(QString());
        USA_resource->setHtml(QCoreApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", nullptr));
        USSR_resource->setHtml(QCoreApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", nullptr));
        btn_next->setText(QCoreApplication::translate("MainWindow", "NEXT", nullptr));
        curr_player_display->setHtml(QCoreApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600;\">USSR</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:28pt; font-weight:600;\"><br /></p></body></html>", nullptr));
        curr_player_head->setHtml(QCoreApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Current Player</span></p></body></html>", nullptr));
        btn_coup->setText(QCoreApplication::translate("MainWindow", "Coup Mode", nullptr));
        round1->setText(QString());
        round2->setText(QString());
        round4->setText(QString());
        round3->setText(QString());
        round5->setText(QString());
        round6->setText(QString());
        round7->setText(QString());
        turn1->setText(QString());
        turn2->setText(QString());
        turn3->setText(QString());
        turn4->setText(QString());
        turn5->setText(QString());
        turn6->setText(QString());
        turn7->setText(QString());
        turn8->setText(QString());
        turn9->setText(QString());
        turn10->setText(QString());
        defcon5->setText(QString());
        defcon4->setText(QString());
        defcon3->setText(QString());
        defcon2->setText(QString());
        defcon1->setText(QString());
        menuTwlight_Struggle_Lite->setTitle(QCoreApplication::translate("MainWindow", "Twlight Struggle Lite", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
