#include "event.h"

// USSR events
EVENT e50("WE WILL BURY YOU", "Perhaps the most famous quote of the entire Cold War, Soviet Premier Nikita Khrushchev uttered this immortal line while addressing Western ambassadors at a reception in Moscow. With these words Khrushchev announced a period during which he would probe the West for weakness and opportunity. The Berlin Crisis exemplified this expansionist policy.", USSR, 4, 0, 0);
EVENT e7("SOCIALIST GOVERNMENT", "Beginning with the end of the Second World War, the US was challenged by democratic leftist movements within its sphere. Italy, under de Gasperi, was particularly contentious with communists and socialists participating in government. The CIA funded an extensive propaganda program against these movements. Socialist governments would be the topic of concern again during the 1960s in France, and with left-wing labor", USSR, 3, 0, 0);
EVENT e51("BERZHNEV DOCTRINE", "Announced to a crowd of Polish workers by Brezhnev himself, the Brezhnev Doctrine clarified the de facto policy of the Soviet Union, the Prague Spring. Namely, current socialist countries would not be allowed to abandon socialism or adopt a position of neutrality. The doctrine contributed to the Soviets’ miscalculation of world reaction to their invasion of Afghanistan. They looked upon the invasion as the mere application of this well-understood doctrine.", USSR, 3, 0, 0);
EVENT e61("OPEC", "Founded to allow oil producing countries to have more control over the price of oil, and thereby state rev-enues, OPEC has grown into an institution that controls two-thirds of the world’s oil reserves and generates roughly half of the world’s oil exports. The creation of OPEC was a major blow to the control of the global oil market by the Western giants like Exxon and British Petroleum. While OPEC does include non-Middle Eastern countries such as Venezuela, Indonesia and Nigeria, it is heavily dominated by countries from that region. As a result, OPEC has intervened in the political crises there. Most famously, OPEC refused oil exports to Western countries supporting Israel in the Yom Kippur (or October) War. This resulted in a 400% increase in oil prices and required rationing in the West. /n /n VP+1", USSR, 3, 1, 0);
EVENT e30("DECOLONIZATION", "While it is hard to put pre-cise dates on the decolonization process, those dates chosen represent two of the most signiﬁcant decolonization successes. Sparking the retreat from empire was Britain’s fulﬁlled promise of independence for India in 1947. At the other extreme, Rhodesia’s ﬁrst majority elections spelled doom for the apartheid system.", USSR, 2, 0, 0);
EVENT e9("VIETNAM REVOLTS", "Ho Chi Minh tried repeatedly to enlist the aid of the Truman Administration for independence. His letters never received a response. The French government, with support from the US and Britain, attempted to reestablish its colony in Indochina. The attempted was doomed and would lead to disaster at Dien Bien Phu. /n /n VP+2", USSR, 2, 2, 0);
EVENT e107("CHE", "Ernesto “Che” Guevara is one of the most widely recognized left-wing icons in the world; his image stares intensely into the distance from T-shirts, mugs, and posters. When he met Fidel Castro in 1955, Guevara knew he had found the cause that he was looking for. He rose quickly in Castro's regard due to his fervor, daring, and charisma, and when the revolutionaries finally overthrew pro-American dictator Fulgencio Batista, Guevara took over command of La Cabana Prison, where he oversaw and carried out thousands of executions for political crimes. Guevara cultivated close ties with the Soviet Union, culminating in the shipment of Soviet nuclear missiles to Cuba (Guevara later said that if he had been in command during the crisis, he would have fired the missiles without hesitation). In 1965, Guevara decided to continue the Cuban Revolution throughout the world, leading communist guerrillas in the Congo and Bolivia. He was captured by Bolivian army forces (with assistance from the CIA) and executed by order of the Bolivian president. He remains a symbol of worldwide leftist revolution. /n /n VP+2", USSR, 3, 2, 0);
EVENT e87("THE REFORMER", "Successor to the short-lived premier-ship of Konstantin Chernenko, Mikhail Gorbachev was the only Soviet leader to be born after the Russian Revolution of 1917. His experience within the Politburo gave him broad exposure to the West which profoundly affected his thinking about the USSR’s future. “Gorby,” as he would be known in the West, inspired a sort of fan following. Margaret Thatcher famously remarked on his coming to power “I like Mr. Gorbachev—we can do business together.” Ultimately, Gorbachev would oversee the dismantling of the Soviet bloc. While his reformist agenda, includ-ing Perestroika (economic reform) and Glasnost (political freedom) made him extremely popular in the West, it made him less so in the Soviet Union. Ultimately, Gorbachev would be removed from ofﬁce as the result of a reactionary military coup in 1991. In the wake of its failure, the Russian Federation would turn to a newly minted hero, Boris Yeltsin.", USSR, 3, 0, 0);
EVENT e90("GLASNOST", "The Russian word for openness, Glasnost was introduced as a public policy by Mikhail Gorbachev. While his long term aim may have been to improve the freedoms of the Russian people, his more immediate goal was to increase pressure on conservative apparatchiks to accept his “perestroika” economic reforms. While the US typically equated Glasnost with freedom of speech, in fact it was an attempt to bring transparency to the workings of the Politburo.", USSR, 4, 0, 0);
EVENT e95("LATIN AMERICAN DEBT CRISIS", "A ripple effect from the rise of Middle Eastern oil, Latin American govern-ments experienced phenomenal growth from the 1950’s into the 1970’s. However, this came to an abrupt halt. Unfortunately, even with impressive economic growth, Latin American countries like Brazil and Ecuador continued to rack up external debt. Given the new found global capital from petrodollars, Latin American govern-ments found willing lenders. External debt in Latin America rose 1,000% from 1970 to 1980. When a global recession sparked by the Iranian oil crisis buffeted world economies, most Latin American governments simply could not keep up. Eventually, these govern-ments would have to commit to signiﬁcant restructuring of their economies to reduce their debt.", USSR, 3, 0, 0);
EVENT* USSR_event_arr[] = {&e50, &e7, &e51, &e61, &e30,
                           &e9, &e107, &e87, &e90, &e95};

// Mutual events
EVENT e34("NUCLEAR TEST BAN", "The ﬁrst Nuclear Test Ban treaty owes its origins to the de-escalation process that followed the Cuban Missile Crisis. It prohibited further nuclear tests in the air, underwater or in space. International pressure for such a ban mounted in the 1950s as scientiﬁc evidence began to document severe environmental damage caused by earlier atmospheric testing by the nuclear powers. Underground testing remained an allowable methodology, but all forms of “peaceful nuclear explosions” were also banned, tightening the non-proliferation regime. /n /n VP+2 DEFCON+2", NO, 4, 2, 2);
EVENT e32("UN INTERVENTION", "The United Nations remained generally unable to inﬂuence the struggle between the superpowers due to Security Council veto power throughout the Cold War. However, it occasionally stood as a gauge for world opinion, and could mediate in stalled conflicts throughout the Third World. It was also the backdrop for a number of quintessential moments of the conﬂict, including the Soviet Korean War walkout, the “We Will Bury You” speech, and of course, the Cuban Missile Crisis—don’t wait for the translation Mr. Zorin!", NO, 3, 0, 0);
EVENT e20("OLYMPIC GAMES", "Sport often served as an outlet for the intense competition between the Superpowers, and that competition was never so intense as at the Olympics. The Olympics served as a test bed to see which society could make the greatest strides in human physical achievement. It ﬁt neatly into Communist ideology of “the New Man.” The games frequently reﬂected the global political situation, as with the terrorist attacks in Munich, and became overt political tools with the US boycott of the Moscow games in 1980, and the Soviet boycott of the LA games in 1984. /n /n VP+2", NO, 2, 2, 0);
EVENT e3("ONE SMALL STEP...", "After years of lagging behind So-viet space exploits, the United States put its full intellectual and economic weight behind the “race to the moon”. President Kennedy initiated Project Mercury. Ul-timately, the National Aeronautics and Space Administration would overcome enormous technological hurdles to place a man on the moon. As Neil Armstrong, the ﬁrst human to set foot upon the moon’s surface, descended from the space craft, he uttered the immortal line “one small step for a man, one giant leap for mankind.” In so doing, he con-ﬁrmed an American come-back victory in the space race between the superpowers.", NO, 3, 0, 0);
EVENT e57("ABM TREATY", "The Anti Ballistic Missile Treaty sought to cement the system of mutually assured destruction as the lynchpin of strategic balance. The ABM treaty restricted the ability of the two superpowers to defend themselves from nuclear strike. In theory, this made a ﬁrst strike to prevent the introduction of destabilizing defensive systems unnecessary. Both nations were allowed to defend either their capital or one ﬁeld of ICBMs with a missile defense system. The Soviets deployed such a system around Moscow. Ultimately, the US abandoned its system deployed in Grand Forks, North Dakota. /n /n DEFCON+2", NO, 3, 0, 2);
EVENT e46("HOW I LEARNED TO STOP WORRYING", "As the reality of nuclear holocaust became accepted by the public, fatalism about its inevitability also took hold. The landmark black comedy, Dr. Strangelove, captured this new mood. However, such attitudes are hardly unique. Similar fatalism about mankind’s ultimate destiny can be found throughout literature of the time and sparked a whole sub-genre of science ﬁction, the post-nuclear-holocaust dime novel ﬁlled with atomic mutants and vague remnants of contemporary civilization. Ironically, the pessimism that is reﬂected in these works may have aided the possibility of nuclear war by making such an act “thinkable.” /n /n DEFCON-2", NO, 2, 0, -2);
EVENT e92("TERRORISM", "While a threat as old as human civilization, the use of terrorism as an instrument to change international policy ebbed and ﬂowed throughout the Cold War. The Soviet Union and its Warsaw Pact allies were known to train terrorist organizations within their borders, including radical elements of the Palestinian Liberation Organization (PLO). In many ways, the PLO provided the archetype for a terrorist organization throughout the Cold War. With its anti-Western, anti-Israel ideology, it became a cause celebre for those asserting that the West was on a neo-imperialist crusade in the third world. Palestinian terrorists hijacked planes, attacked the Achille Lauro, and perhaps most infamously murdered 11 Israeli athletes at the Munich Olympics in 1972. There were also western based, communist afﬁliated terrorists such as the Red Brigades in Italy, and the Red Army in Japan. As the Cold War came to a close, and the Soviet Union faced increasing difﬁculty with Muslim fun-damentalism, its support for terrorism waned.", NO, 3, 0, 0);
EVENT e40("CUBAN MISSILE CRISIS", "The mere mention of this event elicits fears of the nuclear holocaust that almost was. For 14 days in October 1962, the two superpowers seemed destined to clash directly about the Soviet emplace-ment of Medium Range Ballistic Mis-siles (MRBMs) and Intermediate Range Ballistic Missiles (IRBMs) in Cuba. To prevent the installation of additional of-fensive weapons in Cuba, John F. Ken-nedy declared a naval quarantine around Cuba. Tensions reached a near breaking point when a U-2 ﬂight was shot down over Cuba, and Khruschev demanded US missiles be removed from Turkey in exchange for Soviet missiles being removal from Cuba. Ultimately, Khrushchev was compelled to settle for a US pledge not to invade Cuba, and a private agreement to resolve NATO’s missile bases in Turkey. /n /n DEFCON+2", NO, 3, 0, -2);
EVENT e47("JUNTA", "In Spanish, the term Junta means “coming together.” In a Cold War context, it normally refers to the coming together of right wing military cliques to oust an existing government and replace it with a military dictatorship. Juntas were so common in Latin America throughout the period that they became a nearly ritualized affair. More frequently than not, military juntas enjoyed the tacit blessing of the U.S. government as they looked to check leftist elements in Central and South America. Notable juntas include the military dictatorships that ruled Argentina from 1976 to 1983 and Guatemala from 1954 to 1984.", NO, 3, 0, 0);
EVENT e100("WARGAMES", "Brinksmanship was a term coined by John Foster Dulles to describe a policy of coming close to war, without falling into the abyss. At different times, during different crises, this policy was pursued by both superpowers. However, there was always the danger that brinksmanship could turn the “cold” war, hot. Additionally, brinksmanship encouraged a nuclear posture of “launch on warning.” Game theory demanded that if your op-ponent were launching a massive nuclear strike, you would have to launch your own weapons before they could be destroyed in their silos. These doctrines shortened reaction times of world leaders from hours to minutes. On November 9th, 1979, the United States made preparations for a retaliatory nuclear strike when a NORAD computer glitch indicated an all-out Soviet strike had been launched. As recently as 1995, Russia mistook a Norwegian scientiﬁc missile launch for an attack, and Boris Yeltsin was asked to decide whether or not to counterattack.", NO, 4, 0, 0);
EVENT* Mutual_event_arr[] = {&e34, &e32, &e20, &e3, &e57,
                             &e46, &e92, &e40, &e47, &e100};

// USA events
EVENT e74("THE VOICE OF AMERICA", "Formed in 1942 under the War Informa-tion Ofﬁce, the VOA initially broadcast war news into Nazi occupied Europe. In 1947, it altered its mission to begin broadcasting into the Soviet Union. Voice of America has become one of the best known international broadcast efforts in the world. It provided a powerful outside link to the state-controlled media systems of the Eastern Bloc. Together with Radio Free Europe and Radio Free Asia, Voice of America became a hallmark of US public diplomacy efforts dur-ing the Cold War. /n /n VP+1", USA, 3, 1, 0);
EVENT e66("PUPPET GOVERNMENTS", "Not a concept unique to the Cold War, the term “puppet governments” refers to a regime that holds power due to, and with the support of, either the Soviet Union or the United States. A derisive term, it is almost always used by the opponents of a state to undermine the government’s legitimacy. Both the Soviets and the Americans would apply the term to any closely allied state, but it might be better understood in the context of the Diem government in South Vietnam or Mariam government of Ethiopia. /n /n VP+2", USA, 2, 2, 0);
EVENT e23("MARSHALL PLAN", "On June 5, Secretary of State George C. Marshall announced to the world the US plan to reconstruct all of Europe. Due to Soviet pressure, Eastern European states did not participate. However, for the 16 nations of Western Europe that did, the Marshall Plan marked the ﬁrst step on the road to recovery and ultimate victory in the Cold War.", USA, 4, 0, 0);
EVENT e85("STAR WARS", "More properly known as the Strategic Defense Initiative, President Reagan announced this radical depar-ture from the Cold War doctrine of “mutually assured destruction” in a live television speech to the American public. The initial concept for the “space shield” was developed at Lawrence Livermore Na-tional Laboratory by Dr. Peter Hagelstein. Notionally, it would create a series of space based satellites powered by nuclear reactors that would create an impenetrable ﬁeld to block Soviet ICBM’s. While scientiﬁcally sound on paper, the concept was never successfully engineered. Later iterations involved “smart pebbles” and missile based interceptors. SDI is frequently credited as one of the factors that convinced Gorbachev that the Soviet Union could not keep up the Cold War.", USA, 3, 0, 0);
EVENT e106("NORAD", "The North Amercan Aerospace Defense Command is  a joint military organization sponsored by the governments of Canada and the United States. Its mission is to jointly monitor and control the airspace over North America from unfriendly incursion. It was founded to protect against the threat of low-flying Soviet bombers attacking from the Arctic region. During the Cold War, the Command was famously housed in the Cheyenne Mountain facility, depicted in the film WarGames. At its height, NORAD commanded 250,000 military personnel. The command illustrates the full integration and cooperation of US allies into the US nuclear umbrella and alliance structure.", USA, 3, 0, 0);
EVENT e26("CIA", "In an effort to bring to a close the in-ter-service bickering that marred U.S. intelligence during WWII, President Truman created the United States’ ﬁrst independent agency capable both of intelligence analysis and covert operations. Its 40 year cat-and-mouse game with its Soviet counterpart, the KGB, would be the stuff of legend, and one of the hallmarks of the Cold War. /n /n VP+2", USA, 3, 2, 0);
EVENT e21("NATO", "The second part of the US strategy to rebuild Europe, the North Atlantic Treaty Organization (NATO) became synonymous with the West’s opposition to the Soviet Union. An oft repeated maxim for NATO’s purpose captures it nicely: “NATO was created to keep the Soviets out, the Americans in, and the Germans down.”", USA, 4, 0, 0);
EVENT e96("TEAR DOWN THIS WALL", "In a speech that hearkened back to Kennedy’s address in front of the Berlin wall, Ronald Reagan challenged newly installed Soviet leader Mikhail Gorbachev. Reagan, with the Brandenburg gate in the background, declared: “General Secretary Gorbachev, if you seek peace, if you seek prosperity for the Soviet Union and Eastern Europe, if you seek liberalization: Come here to this gate! Mr. Gorbachev, open this gate! Mr. Gorbachev, tear down this wall!” While provocative, the speech leveled a difﬁcult criticism at the Soviet Union. Successful countries do not have to wall their citizens in. Two short years later, the Berlin Wall would come down. /n /n VP+3", USA, 3, 3, 0);
EVENT e29("EAST EUROPEAN UNREST", "Captured most visibly by Nagy’s attempt to withdraw Hungary from the Warsaw Pact and Czechoslovakia’s Prague Spring of 1968, members of the Warsaw Pact frequently sought to loosen the reins of Moscow. When taken too far, from the Soviet perspective, the ef-fects could be devastating. Soviet tanks became a universal symbol of Soviet determination to hold on to Eastern Eu-rope, through undisguised oppression if necessary. /n /n VP+2", USA, 3, 2, 0);
EVENT e77("“ASK NOT WHAT YOUR COUNTRY CAN DO FOR YOU...”", "The seminal line of perhaps the most powerful inaugural address ever given by a US president, President Kennedy ushered in an era of American conﬁdence and resolve during the Cold War. Popular with American youth, Kennedy inspired a renewed dedication for public service both with ambitious goals for government sponsored science and youth oriented public service like the Peace Corps. His call for selﬂess dedication to the needs of the nation reﬂected the passion of a restless generation of young Americans eager to make their mark upon the world. /n /n VP+1", USA, 3, 1, 0);
EVENT* USA_event_arr[] = {&e74, &e66, &e23, &e85, &e106,
                          &e26, &e21, &e96, &e29, &e77};















